version: '3.9'
 
services:
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql
    environment:
      - POSTGRES_DB=jcode-test-db1
      - POSTGRES_USER=${POSTGRES_USER:-dimon}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-11111111}
    ports:
      - "5432:5432"
    restart: always
    #volumes:
      #- ./init:/docker-entrypoint-initdb.d/
    networks:
      - app-network    

  app:
    #container_name: jcode-test
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context:  ~/Documents/Workspace/java-projects/jcode-test
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://localhost:5432/jcode-test-db1
      - DB_USERNAME=${POSTGRES_USER:-dimon}
      - DB_PASSWD=${POSTGRES_PASSWORD:-11111111}
      - SERVER_PORT=10100
    expose:
      - "10100"
    depends_on:
      - postgresql
    restart: always
    networks:
      - app-network    

networks:
  app-network:
    driver: bridge
